import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {keccak,selector,fromHex} from '../src/ens/keccak.mjs';
import {encode,decode,tuple,array,callData} from '../src/ens/abi.mjs';
import {dnsName,namehash,normalizeName,ABI,RESOLVER_ROLE,setterResource} from '../src/ens/protocol.mjs';
import {FlyEngine,initialState} from '../src/sim/engine.mjs';import {validateCircuit} from '../src/sim/circuit.mjs';
import {canonical,modelDigest,sha256,makeCheckpoint,verifyCheckpoint,validateCheckpoint,safeCheckpointURL} from '../src/sim/checkpoint.mjs';
const graph=JSON.parse(await readFile(new URL('../data/circuit.json',import.meta.url),'utf8')),hash=await modelDigest(graph);
const state=()=>initialState('agent-one',1234,graph.nodes.length);
async function fixture(){const engine=new FlyEngine(graph,state());for(let i=0;i<150;i++)engine.step();const cp=makeCheckpoint(engine.snapshot(),hash,1),raw=canonical(cp);return{engine,cp,raw,pointer:{schema:'flyns.pointer.v1',uri:'https://example.test/cp.json',sha256:await sha256(raw),sequence:1}};}
const expected={agentId:'agent-one',modelHash:hash,neuronCount:graph.nodes.length};
test('Keccak-256 standard empty vector',()=>assert.equal(keccak(''),'0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470'));
test('Keccak-256 abc vector',()=>assert.equal(keccak('abc'),'0x4e03657aea45a94fc7d47ba826c8d667c0d1e6e33a64a036ec44f58fa12d6c45'));
test('Ethereum function selector known vector',()=>assert.equal(selector('transfer(address,uint256)'),'0xa9059cbb'));
test('ENS namehash known eth vector',()=>assert.equal(namehash('eth'),'0x93cdeb708b7545dc668eb9280176169d1c33cfd8ed6f04690a0bcc88a93fc4ae'));
test('DNS wire encoding includes byte lengths and terminator',()=>assert.equal(dnsName('ada.flyns.eth'),'0x0361646105666c796e730365746800'));
test('Normalization is intentionally ASCII-only, not Unicode approximation',()=>{assert.equal(normalizeName('ADA.ETH'),'ada.eth');for(const s of ['a..eth',' ada.eth','-ada.eth','ada-.eth','초파리.eth','a'.repeat(64)+'.eth'])assert.throws(()=>normalizeName(s));});
test('Strict input hex validation',()=>{assert.throws(()=>fromHex('0xabc'));assert.throws(()=>fromHex('0xzz'));});
test('Static ABI matches fixed known layout',()=>assert.equal(encode(['uint256','bool'],[42n,true]),'0x'+'2a'.padStart(64,'0')+'1'.padStart(64,'0')));
test('String ABI uses 32-byte offset, byte length and padding',()=>assert.equal(encode(['string'],['abc']),'0x'+'20'.padStart(64,'0')+'3'.padStart(64,'0')+'616263'.padEnd(64,'0')));
test('Nested resolver initializer round trip',()=>{const types=[array(tuple('address','uint256')),array('bytes')],v=[[['0x'+'12'.repeat(20),5n]],['0x1234','0x']];assert.deepEqual(decode(types,encode(types,v)),v);});
test('Static getState tuple round trip',()=>{const t=ABI.state.out,v=[[2n,123456n,'0x'+'34'.repeat(20),55n,66n]];assert.deepEqual(decode(t,encode(t,v)),v);});
test('ABI rejects bad addresses, arity and overflowing uint64',()=>{assert.throws(()=>encode(['address'],['0x12']));assert.throws(()=>encode(['uint64'],[1n<<64n]));assert.throws(()=>encode(['uint256'],[]));});
test('ABI rejects truncated and invalid bool results',()=>{assert.throws(()=>decode(['string'],'0x'));assert.throws(()=>decode(['bool'],encode(['uint256'],[2n])));});
test('Key permission resource is key keccak, not agent namehash',()=>{assert.equal(setterResource('flyns.checkpoint'),BigInt(keccak('flyns.checkpoint')));assert.equal(RESOLVER_ROLE.TEXT,16n);assert.ok(callData(ABI.setText.sig,ABI.setText.in,[dnsName('ada.eth'),'flyns.checkpoint','x']).startsWith(selector('setText(bytes,string,string)')));});
test('Circuit validation rejects invented invalid edge indices',()=>{const g=structuredClone(graph);g.edges.push([0,999999,1]);assert.throws(()=>validateCircuit(g));});
test('Circuit validation rejects duplicate directed edges',()=>{const g=structuredClone(graph);g.edges.push(g.edges[0]);assert.throws(()=>validateCircuit(g));});
test('Separate identical seeded runtimes are deterministic',()=>{const a=new FlyEngine(graph,state()),b=new FlyEngine(graph,state());for(let i=0;i<400;i++){a.step();b.step();}assert.deepEqual(a.snapshot(),b.snapshot());});
test('Each agent owns an independent neural array and PRNG state',()=>{const s=state(),a=new FlyEngine(graph,s),b=new FlyEngine(graph,s);a.step();assert.equal(b.state.tick,0);assert.notDeepEqual(a.state.neural,b.state.neural);assert.notEqual(a.state.rng,b.state.rng);assert.equal(s.tick,0);});
test('Measured circuit edges affect this engineered model, not a biological validation',()=>{const a=new FlyEngine(graph,state()),b=new FlyEngine(graph,state(),{silenced:true});for(let i=0;i<200;i++){a.step();b.step();}assert.notDeepEqual(a.state.neural,b.state.neural);});
test('Canonical object order is stable',()=>assert.equal(canonical({b:2,a:[1,true]}),canonical({a:[1,true],b:2})));
test('Canonical JSON rejects nonfinite values',()=>assert.throws(()=>canonical({a:NaN})));
test('Model digest includes graph and engine configuration',async()=>{const other=structuredClone(graph);other.edges[0][2]++;assert.notEqual(await modelDigest(other),hash);});
test('Verified checkpoint preserves next 100 exact simulation steps',async()=>{const {engine,raw,pointer}=await fixture(),cp=await verifyCheckpoint(raw,pointer,expected),restored=new FlyEngine(graph,cp.state);for(let i=0;i<100;i++){engine.step();restored.step();}assert.deepEqual(engine.snapshot(),restored.snapshot());});
test('Tampered checkpoint bytes are rejected',async()=>{const {raw,pointer}=await fixture();await assert.rejects(verifyCheckpoint(raw+' ',pointer,expected),/integrity/);});
test('Different agent identity is rejected',async()=>{const {raw,pointer}=await fixture();await assert.rejects(verifyCheckpoint(raw,pointer,{...expected,agentId:'another'}),/identity/);});
test('Different model is rejected',async()=>{const {raw,pointer}=await fixture();await assert.rejects(verifyCheckpoint(raw,pointer,{...expected,modelHash:'a'.repeat(64)}),/Model/);});
test('Stale checkpoint sequence is rejected',async()=>{const {raw,pointer}=await fixture();await assert.rejects(verifyCheckpoint(raw,pointer,{...expected,minSequence:2}),/stale/);});
test('Pointer and snapshot sequence must agree',async()=>{const {raw,pointer}=await fixture();await assert.rejects(verifyCheckpoint(raw,{...pointer,sequence:2},expected),/sequence/);});
test('Checkpoint validation catches dimensions and poisoned neural values',async()=>{const {cp}=await fixture();cp.state.neural=[0,0];assert.throws(()=>validateCheckpoint(cp,expected),/neural/);cp.state.neural=Array(graph.nodes.length).fill(-1);assert.throws(()=>validateCheckpoint(cp,expected),/neural/);});
test('Checkpoint rejects zero PRNG, unsupported schema and infinite pose',async()=>{const {cp}=await fixture();let c=structuredClone(cp);c.state.rng=0;assert.throws(()=>validateCheckpoint(c));c=structuredClone(cp);c.schema='future';assert.throws(()=>validateCheckpoint(c));c=structuredClone(cp);c.state.x=Infinity;assert.throws(()=>validateCheckpoint(c));});
test('Checkpoint URLs must be HTTPS or same-origin localhost',()=>{const base='http://localhost:4173/';assert.equal(safeCheckpointURL('/checkpoints/x',base),'http://localhost:4173/checkpoints/x');for(const u of ['javascript:alert(1)','http://evil.test/x','http://localhost:9999/x','https://u:p@example.test/x'])assert.throws(()=>safeCheckpointURL(u,base));});
