import test from 'node:test';import assert from 'node:assert/strict';import {LocalENS} from '../src/ens/local.mjs';import {WalletRPC} from '../src/ens/rpc.mjs';import {ABI,dnsName} from '../src/ens/protocol.mjs';
const h='a'.repeat(64),ptr={schema:'flyns.pointer.v1',uri:'https://example.test/a',sha256:h,sequence:1};
async function colony(){const ens=new LocalENS(),a=await ens.hatch('ada',{agentId:'a',modelHash:h}),b=await ens.hatch('kibo',{agentId:'b',modelHash:h});return{ens,a,b};}
test('Local rights: runtime cannot create identities',async()=>{const {ens}=await colony();ens.as('runtime');await assert.rejects(ens.hatch('mori',{agentId:'c',modelHash:h}),/DENIAL/);});
test('Local rights: delegation applies to exactly one resolver',async()=>{const{ens,a,b}=await colony();assert.notEqual(a.resolver,b.resolver);await ens.grant(a);ens.as('runtime');await ens.publish(a,ptr);await assert.rejects(ens.publish(b,ptr),/DENIAL/);});
test('Local rights: checkpoint grant does not permit model changes',async()=>{const{ens,a}=await colony();await ens.grant(a);ens.as('runtime');await assert.rejects(ens.probeForbidden(a),/DENIAL/);});
test('Local rights: revoke blocks subsequent canonical writes',async()=>{const{ens,a}=await colony();await ens.grant(a);ens.as('runtime');await ens.publish(a,ptr);ens.as('owner');await ens.revoke(a);ens.as('runtime');await assert.rejects(ens.publish(a,{...ptr,sequence:2}),/revoked/);assert.deepEqual(await ens.checkpoint(a.name),ptr);});
test('Local aliases follow current records, not a copied snapshot',async()=>{const{ens,a}=await colony();const alias=await ens.alias(a);await ens.publish(a,ptr);assert.equal((await ens.getAgent(alias)).agentId,a.agentId);await ens.publish(a,{...ptr,sequence:2});assert.equal((await ens.checkpoint(alias)).sequence,2);});
test('Local runtime cannot mint or relink aliases',async()=>{const{ens,a}=await colony();ens.as('runtime');await assert.rejects(ens.alias(a),/DENIAL/);});
function mock({wrongChain=false,changedAccount=false,preflightFail=false,reverted=false}={}){const calls=[],events=[],account='0x'+'11'.repeat(20),hash='0x'+'ab'.repeat(32);const provider={request:async({method,params})=>{calls.push({method,params});if(method==='eth_requestAccounts')return[account];if(method==='eth_accounts')return[changedAccount?'0x'+'22'.repeat(20):account];if(method==='eth_chainId')return wrongChain?'0x1':'0xaa36a7';if(method==='eth_call'){if(preflightFail)throw new Error('execution reverted: not authorized');return'0x';}if(method==='eth_sendTransaction')return hash;if(method==='eth_getTransactionReceipt')return{status:reverted?'0x0':'0x1',blockNumber:'0xa',transactionHash:hash};throw new Error('Unexpected method '+method);}};const rpc=new WalletRPC(provider,e=>events.push(e));rpc.account=account;return{rpc,calls,events};}
const send=rpc=>rpc.send('0x'+'44'.repeat(20),ABI.setText,[dnsName('ada.eth'),'flyns.checkpoint','test'],'checkpoint');
test('Live RPC guard rejects wrong chain before signing',async()=>{const{rpc,calls}=mock({wrongChain:true});await assert.rejects(send(rpc),/Wrong chain/);assert.ok(!calls.some(c=>c.method==='eth_sendTransaction'));});
test('Live RPC guard rejects account switches before signing',async()=>{const{rpc,calls}=mock({changedAccount:true});await assert.rejects(send(rpc),/account changed/);assert.ok(!calls.some(c=>c.method==='eth_sendTransaction'));});
test('Failed eth_call preflight is not submitted or counted as a mined revert',async()=>{const{rpc,calls,events}=mock({preflightFail:true});await assert.rejects(send(rpc),/reverted/);assert.ok(!calls.some(c=>c.method==='eth_sendTransaction'));assert.equal(events.length,0);});
test('Live RPC only marks confirmed after success receipt (mock transport)',async()=>{const{rpc,events}=mock();await send(rpc);assert.deepEqual(events.map(e=>e.kind),['pending','confirmed']);assert.equal(events[1].block,10);assert.equal(events[1].receipt.status,'0x1');assert.equal(events[1].receipt.transactionHash,events[1].hash);});
test('Reverted receipt is never marked successful (mock transport)',async()=>{const{rpc,events}=mock({reverted:true});await assert.rejects(send(rpc),/reverted/);assert.deepEqual(events.map(e=>e.kind),['pending','reverted']);});
