import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createApp} from '../server.mjs';import {initialState} from '../src/sim/engine.mjs';import {canonical,makeCheckpoint,sha256,modelDigest} from '../src/sim/checkpoint.mjs';
const graph=JSON.parse(await readFile(new URL('../data/circuit.json',import.meta.url),'utf8'));const raw=canonical(makeCheckpoint(initialState('api-test',77,graph.nodes.length),await modelDigest(graph),1));
async function withServer(fn){const dir=await mkdtemp(join(tmpdir(),'flyns-test-')),server=createApp({storageDir:dir});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;try{await fn(base);}finally{await new Promise(r=>server.close(r));await rm(dir,{recursive:true,force:true});}}
test('Server health reports the actual storage backend',()=>withServer(async base=>{const r=await fetch(base+'/api/health');assert.equal(r.status,200);assert.equal((await r.json()).storage,'content-addressed-files');}));
test('Server stores immutable bytes and returns their actual SHA-256',()=>withServer(async base=>{const r=await fetch(base+'/api/checkpoints',{method:'POST',headers:{origin:base},body:raw});assert.equal(r.status,201);const p=await r.json();assert.equal(p.sha256,await sha256(raw));const saved=await fetch(p.uri);assert.equal(await saved.text(),raw);assert.match(saved.headers.get('cache-control'),/immutable/);}));
test('Repeated content uploads are idempotent',()=>withServer(async base=>{const post=async()=>{const r=await fetch(base+'/api/checkpoints',{method:'POST',body:raw});assert.equal(r.status,201);return r.json();};assert.deepEqual(await post(),await post());}));
test('Server rejects foreign-origin uploads',()=>withServer(async base=>assert.equal((await fetch(base+'/api/checkpoints',{method:'POST',headers:{origin:'https://evil.test'},body:raw})).status,403)));
test('Server rejects invalid checkpoint JSON and schemas',()=>withServer(async base=>{for(const body of ['not json','{"schema":"wrong"}'])assert.equal((await fetch(base+'/api/checkpoints',{method:'POST',body})).status,400);}));
test('Secrets and non-asset paths are never served',()=>withServer(async base=>{for(const path of ['/.env','/server.mjs','/.storage/checkpoints/x','/tests/core.test.mjs','/src/%2e%2e/%2e%2e/etc/passwd'])assert.equal((await fetch(base+path)).status,404);}));
test('Served HTML has a restrictive script CSP',()=>withServer(async base=>{const r=await fetch(base+'/');assert.equal(r.status,200);assert.match(r.headers.get('content-security-policy'),/script-src 'self'/);assert.match(await r.text(),/LOCAL REHEARSAL/);}));
