import {readFile, writeFile, mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';

// Pinned from the official ENS Sepolia beta deployment table, not a moving branch.
const commit = '71a3b7339dbc55ab47667abdfe8303bac4f4c24e';
const contracts = {
  VerifiableFactory: 'factory', ETHRegistry: 'ethRegistry',
  UserRegistryImpl: 'registryImplementation', PermissionedResolverImpl: 'resolverImplementation',
  UpgradableUniversalResolverProxy: 'universalResolver', UniversalResolverV2: null,
};
const operations = {
  deploy: ['VerifiableFactory', 'deployProxy'], verify: ['VerifiableFactory', 'verifyContract'],
  initRegistry: ['UserRegistryImpl', 'initialize'], initResolver: ['PermissionedResolverImpl', 'initialize'],
  register: ['UserRegistryImpl', 'register'], setParent: ['UserRegistryImpl', 'setParent'],
  setSubregistry: ['ETHRegistry', 'setSubregistry'], state: ['ETHRegistry', 'getState'],
  subregistry: ['ETHRegistry', 'getSubregistry'], resolver: ['UserRegistryImpl', 'getResolver'],
  hasRoles: ['PermissionedResolverImpl', 'hasRoles'], hasRootRoles: ['PermissionedResolverImpl', 'hasRootRoles'],
  setText: ['PermissionedResolverImpl', 'setText'], setAddress: ['PermissionedResolverImpl', 'setAddress'],
  grantSetter: ['PermissionedResolverImpl', 'grantSetterRoles'], revoke: ['PermissionedResolverImpl', 'revokeRoles'],
  link: ['PermissionedResolverImpl', 'linkToNode'], resolve: ['UniversalResolverV2', 'resolve'],
  decodeSetter: ['PermissionedResolverImpl', 'decodeSetter'], rootRegistry: ['UniversalResolverV2', 'ROOT_REGISTRY'],
};
const config = JSON.parse(await readFile('public/config.json', 'utf8'));
const artifacts = {}, sources = [];
for (const [name, key] of Object.entries(contracts)) {
  const url = `https://raw.githubusercontent.com/ensdomains/contracts-v2/${commit}/contracts/deployments/sepolia/${name}.json`;
  const response = await fetch(url, {signal: AbortSignal.timeout(30000)});
  if (!response.ok) throw new Error(`${name}: HTTP ${response.status}`);
  const raw = await response.text(), artifact = JSON.parse(raw);
  if (key) assert.equal(config[key].toLowerCase(), artifact.address.toLowerCase(), `Address mismatch: ${key}`);
  artifacts[name] = artifact;
  sources.push({name, url, address: artifact.address, sha256: createHash('sha256').update(raw).digest('hex')});
}
const functions = Object.fromEntries(Object.entries(operations).map(([key, [name, method]]) => {
  const matches = artifacts[name].abi.filter(item => item.type === 'function' && item.name === method);
  assert.equal(matches.length, 1, `Expected one official ABI for ${key}`);
  return [key, matches[0]];
}));
// These functions are resolver-profile calldata, not direct methods of ENSv2.
// ENSIP-1/5 profiles are dispatched inside UniversalResolver.resolve(bytes,bytes).
const profiles = {
  textProfile: {type: 'function', name: 'text', stateMutability: 'view', inputs: [{type:'bytes32'}, {type:'string'}], outputs:[{type:'string'}]},
  addrProfile: {type: 'function', name: 'addr', stateMutability: 'view', inputs: [{type:'bytes32'}], outputs:[{type:'address'}]},
};
const permissionError = artifacts.PermissionedResolverImpl.abi.find(item => item.type === 'error' && item.name === 'EACUnauthorizedAccountRoles');
assert.ok(permissionError);
const manifest = {commit, sources, functions: Object.keys(functions), profiles: 'ENSIP-1/5; https://docs.ens.domains/ensv2/permissioned-resolver/'};
await mkdir('docs/evidence', {recursive: true});
await writeFile('docs/evidence/ens-abi-manifest.json', JSON.stringify(manifest, null, 2) + '\n');
await writeFile('src/ens/official-abis.mjs', `// Generated by npm run sync:ens-abi from ENS contracts-v2 ${commit}.\n// Official contracts are MIT licensed; see docs/evidence/ens-abi-manifest.json.\nexport const OFFICIAL_FUNCTIONS = ${JSON.stringify({...functions, ...profiles}, null, 2)};\nexport const PERMISSION_ERROR_ABI = ${JSON.stringify([permissionError])};\n`);
console.log(`Verified five configured addresses; generated ${Object.keys(functions).length} official function ABIs and two standard profiles.`);
