// Generated by npm run sync:ens-abi from ENS contracts-v2 71a3b7339dbc55ab47667abdfe8303bac4f4c24e.
// Official contracts are MIT licensed; see docs/evidence/ens-abi-manifest.json.
export const OFFICIAL_FUNCTIONS = {
  "deploy": {
    "inputs": [
      {
        "internalType": "address",
        "name": "implementation",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "salt",
        "type": "uint256"
      },
      {
        "internalType": "bytes",
        "name": "data",
        "type": "bytes"
      }
    ],
    "name": "deployProxy",
    "outputs": [
      {
        "internalType": "address",
        "name": "proxy",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  "verify": {
    "inputs": [
      {
        "internalType": "address",
        "name": "proxy",
        "type": "address"
      }
    ],
    "name": "verifyContract",
    "outputs": [
      {
        "internalType": "address",
        "name": "implementation",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  "initRegistry": {
    "inputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "account",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "roleBitmap",
            "type": "uint256"
          }
        ],
        "internalType": "struct Grant[]",
        "name": "grants",
        "type": "tuple[]"
      }
    ],
    "name": "initialize",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  "initResolver": {
    "inputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "account",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "roleBitmap",
            "type": "uint256"
          }
        ],
        "internalType": "struct Grant[]",
        "name": "grants",
        "type": "tuple[]"
      },
      {
        "internalType": "bytes[]",
        "name": "calls",
        "type": "bytes[]"
      }
    ],
    "name": "initialize",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  "register": {
    "inputs": [
      {
        "internalType": "string",
        "name": "label",
        "type": "string"
      },
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      },
      {
        "internalType": "contract IRegistry",
        "name": "registry",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "resolver",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "roleBitmap",
        "type": "uint256"
      },
      {
        "internalType": "uint64",
        "name": "expiry",
        "type": "uint64"
      }
    ],
    "name": "register",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  "setParent": {
    "inputs": [
      {
        "internalType": "contract IRegistry",
        "name": "parent",
        "type": "address"
      },
      {
        "internalType": "string",
        "name": "label",
        "type": "string"
      }
    ],
    "name": "setParent",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  "setSubregistry": {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "anyId",
        "type": "uint256"
      },
      {
        "internalType": "contract IRegistry",
        "name": "registry",
        "type": "address"
      }
    ],
    "name": "setSubregistry",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  "state": {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "anyId",
        "type": "uint256"
      }
    ],
    "name": "getState",
    "outputs": [
      {
        "components": [
          {
            "internalType": "enum IPermissionedRegistry.Status",
            "name": "status",
            "type": "uint8"
          },
          {
            "internalType": "uint64",
            "name": "expiry",
            "type": "uint64"
          },
          {
            "internalType": "address",
            "name": "latestOwner",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "tokenId",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "resource",
            "type": "uint256"
          }
        ],
        "internalType": "struct IPermissionedRegistry.State",
        "name": "state",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  "subregistry": {
    "inputs": [
      {
        "internalType": "string",
        "name": "label",
        "type": "string"
      }
    ],
    "name": "getSubregistry",
    "outputs": [
      {
        "internalType": "contract IRegistry",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  "resolver": {
    "inputs": [
      {
        "internalType": "string",
        "name": "label",
        "type": "string"
      }
    ],
    "name": "getResolver",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  "hasRoles": {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "resource",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "roleBitmap",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "hasRoles",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  "hasRootRoles": {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "roleBitmap",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "hasRootRoles",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  "setText": {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "name",
        "type": "bytes"
      },
      {
        "internalType": "string",
        "name": "key",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "value",
        "type": "string"
      }
    ],
    "name": "setText",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  "setAddress": {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "name",
        "type": "bytes"
      },
      {
        "internalType": "uint256",
        "name": "coinType",
        "type": "uint256"
      },
      {
        "internalType": "bytes",
        "name": "addressBytes",
        "type": "bytes"
      }
    ],
    "name": "setAddress",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  "grantSetter": {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "setter",
        "type": "bytes"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "grantSetterRoles",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  "revoke": {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "resource",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "roleBitmap",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "revokeRoles",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  "link": {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "sourceName",
        "type": "bytes"
      },
      {
        "internalType": "bytes32",
        "name": "targetNode",
        "type": "bytes32"
      }
    ],
    "name": "linkToNode",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  "resolve": {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "name",
        "type": "bytes"
      },
      {
        "internalType": "bytes",
        "name": "data",
        "type": "bytes"
      }
    ],
    "name": "resolve",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  "decodeSetter": {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "setter",
        "type": "bytes"
      }
    ],
    "name": "decodeSetter",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "arg",
        "type": "bytes"
      },
      {
        "internalType": "uint256",
        "name": "resource",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "roleBitmap",
        "type": "uint256"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  "rootRegistry": {
    "inputs": [],
    "name": "ROOT_REGISTRY",
    "outputs": [
      {
        "internalType": "contract IPermissionedRegistry",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  "textProfile": {
    "type": "function",
    "name": "text",
    "stateMutability": "view",
    "inputs": [
      {
        "type": "bytes32"
      },
      {
        "type": "string"
      }
    ],
    "outputs": [
      {
        "type": "string"
      }
    ]
  },
  "addrProfile": {
    "type": "function",
    "name": "addr",
    "stateMutability": "view",
    "inputs": [
      {
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "type": "address"
      }
    ]
  }
};
export const PERMISSION_ERROR_ABI = [{"inputs":[{"internalType":"uint256","name":"resource","type":"uint256"},{"internalType":"uint256","name":"roleBitmap","type":"uint256"},{"internalType":"address","name":"account","type":"address"}],"name":"EACUnauthorizedAccountRoles","type":"error"}];
